### ISSUE TITLE
Domain in FAST.Farm example 1 

### ISSUE THREAD

**Issue by MaximilienAndre** [OpenFAST/openfast_toolbox#14]
Dear all, 

I have recently had issues with the domain discretization in FAST.Farm. My main issue is that I am not able to find the good trade off between the domain recommendations in OpenFAST readthedocs 4.2.15.6 and what is "realistic" in term of TurbSim grid size, knowing that past ~60*60 grid it is not possible to run TurbSim anymore. 

To understand better how this work, I am running again the examples in the toolbox and I have a question regarding example 1. 

In this example, we set a TurbSim input file for a FAST.Farm simulation. We have no specifications regarding the FAST.Farm case, so I assume the Inflow type is "ModAmbWind = 2" where there is only one input file at the entrance of the FAST.Farm domain. According to the guidances in 4.2.15.4.4, when doing so the TurbSim grid shall have the resolution of FAST.Farm HighRes grids. 

 However, to do so we use the "TSCaseCreation" class, without specifying the "high_ext" parameter, thus it defaults to 1.2. The inflow file has thus a grid spanning from y0-0.6D to y0+0.6D. However, this grid is too small because according to 4.2.15.6.4.1.1 the domain should extend at least from y0-3D to y0+3D. 

It seems that this is an error in the example.  

I suggest fixing it by specifying "high_ext" in line 37 of Ex1_TurbSimInputSetup.py

`Case = TSCaseCreation(D, HubHt, Vhub, TI, PLExp, x=xlocs, y=ylocs, zbot=zbot, cmax=cmax, fmax=fmax, Cmeander=Cmeander,high_ext=7)`

This sets a grid of appropriate size, however with its dimension of 167*109 it is in practice impossible to run with TurbSim... 

Do you have recommendation on the best way to fix this situation ? 

Best, 

Max 

PS : I would really appreciate any example running with ModAmbWind=3 at it seems much more practical than ModAmbWind=2, please tell me if some ressources are available.  

Best,

**Comment by MaximilienAndre** [comment]
I have noticed a second issue related to domain extent. In the `fastfarm/fastfarm.py` library. When defining the "ambient wind" domain, the Yo value is set at line 245 

`    Y0_Low = np.floor( -max([abs(Y) for Y in yWT]) -extent_YZ*D - dY_Low )`

However this again is not what indicated in 4.2.15.6.4.1.1 because here "extent_YZ" refers to the value from the high_res box as mentionned in line 197 

`     - extent_YZ      : y-extent of high-res box (in diameter) around turbine location`

So with a typical value of 1.2 w get Y0_Low ~= Y0_WT - 1.2 D which gives a box too narrow compared to the Y0-3D, Y0+3D.

Best, 

Max

**Comment by rthedin** [comment]
We recommend running TurbSim within your setup for FAST.Farm. The setup for TurbSim depends on your farm, which needs to be consistent with your FAST.Farm setup. Instead of using the `TSCaseCreation` class on its own, you should be using the [`FFCaseCreation`](https://github.com/OpenFAST/openfast_toolbox/blob/353643ed917d113ec8dfd765813fef7d09752757/openfast_toolbox/fastfarm/FASTFarmCaseCreation.py#L60) one. Note that `TSCaseCreation` is called within `FFCaseCreation`. To run FAST.Farm using `Mod_AmbWind` 3, follow the example provided [here](https://github.com/OpenFAST/openfast_toolbox/blob/main/openfast_toolbox/fastfarm/examples/Ex3_FFarmCompleteSetup.py).

To your specific points, the `high_ext` [defaulting to 1.2](https://github.com/OpenFAST/openfast_toolbox/blob/353643ed917d113ec8dfd765813fef7d09752757/openfast_toolbox/fastfarm/FASTFarmCaseCreation.py#L346) is for the high-resolution boxes, using when `Mod_AmbWind` is 3. [It defaults](https://github.com/OpenFAST/openfast_toolbox/blob/353643ed917d113ec8dfd765813fef7d09752757/openfast_toolbox/fastfarm/FASTFarmCaseCreation.py#L345) to a larger value for the low-res box.

**Comment by MaximilienAndre** [comment]
Thank you very much for your answer, I will try this and get back to you as soon as I can make it work. 

Best, 

Max

**Comment by rthedin** [comment]
Closing this. Feel free to reopen if you have further issues.
